repos:
- repo: local
  hooks:
  - id: unit tests
    name: Set of unit tests
    entry: pytest tests/unit/
    language: system
    always_run: true
    pass_filenames: false
  - id: ruff 
    name: Ruff
    entry: ruff check src/ tests/unit/ tests/integration/ --fix
    language: system
    always_run: true
    pass_filenames: false
  - id: pyright
    name: Pyright
    entry: pyright src/
    language: system
    always_run: true
    pass_filenames: false
