[tool.pyright]
typeCheckingMode = "strict"
reportMissingTypeArgument = true
reportMissingParameterType = true
reportInvalidTypeVarUse = true

[tool.ruff]
select = ["E", "F", "B", "E", "W", "Q", "N", "D", "ANN", "C4", "SIM", "ARG"]
ignore = ["E501"]
unfixable = ["B"]

target-version = "py311"
line-length = 88

[tool.ruff.per-file-ignores]
"__init__.py" = ["E402", "D104"]
"path/to/file.py" = ["E402"]
"**/{tests,docs,tools}/*" = ["E402"]

[tool.ruff.flake8-quotes]
docstring-quotes = "double"